FROM nginx

RUN \
  apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/* && \
  git clone https://github.com/taigaio/taiga-front-dist.git  /usr/local/taiga/taiga-front/ && \
  cd /usr/local/taiga/taiga-front/ && \
  git checkout stable
COPY conf.json /usr/local/taiga/taiga-front/dist/js/conf.json
COPY entrypoint.sh /usr/local/taiga/entrypoint.sh
COPY nginx.conf /etc/nginx/nginx.conf
COPY server.conf /etc/nginx/conf.d/default.conf

RUN chmod -R 755 /usr/local/taiga/taiga-front/dist && chmod +x /usr/local/taiga/entrypoint.sh

CMD ["/usr/local/taiga/entrypoint.sh"]